CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(64) NOT NULL,
    type VARCHAR(10) NOT NULL,
    created_on DATETIME DEFAULT NOW()
);

CREATE TABLE products (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    price INT NOT NULL,
    created_on DATETIME DEFAULT NOW(),
    sellerId INT NOT NULL FOREIGN KEY REFERENCES users(id)
);

CREATE TABLE orders (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_on DATETIME DEFAULT NOW(),
    productId INT NOT NULL FOREIGN KEY REFERENCES products(id),
    buyerId INT NOT NULL FOREIGN KEY REFERENCES users(id),
);
